---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app   # <APP_NAME> more in the readme
  namespace: default  
  labels:
    app: flask-app
    # app.kubernetes.io/name: "flask-store"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
      # annotations:
      #   app.kubernetes.io/name: "flask-store"
        # eks.amazonaws.com/fargate-profile: "default"
    spec:
      containers:
      - name: flask-app
        image: AccID.dkr.ecr.us-east-2.amazonaws.com/flask-app:v1   # <ECR_REGISTRY>/<ECR_REPOSITORY>:v1 more in the readme
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP