---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app   # <APP_NAME> please refer to the readme
  namespace: default  
  labels:
    app: flask-app  # <APP_NAME> please refer to the readme
    # app.kubernetes.io/name: "flask-store"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
      # annotations:
      #   app.kubernetes.io/name: "flask-store"
        # eks.amazonaws.com/fargate-profile: "default"
    spec:
      containers:
      - name: flask-app
        image: AccID.dkr.ecr.us-east-2.amazonaws.com/flask-app:v1   # <ECR_REGISTRY>/<ECR_REPOSITORY>:v1 please refer to the readme
        ports:
        - containerPort: 5000             # <CONTAINER_PORT> please refer to the readme
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app      # <APP_NAME> please refer to the readme
  namespace: default
  labels:
    app: flask-app     # <APP_NAME> please refer to the readme
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80            # <SERVICE_PORT> please refer to the readme
      targetPort: 5000    # <TARGET_PORT>  please refer to the readme
      protocol: TCP