name: Deploy to EKS

on:
  push:
    branches:
      - master
      - feat/cicd-pipeline
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Verify variables 
        run: echo $AWS_REGION && echo $EKS_CLUSTER_NAME

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_oidc_role }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Debug AWS Caller Identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest -f flask-service/Dockerfile  flask-service
      
      - name: Tag and push Docker image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
      
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.EKS_CLUSTER_NAME }}

      - name: Check cluster config
        run: kubectl get nodes -v=10

      - name: Deploy to EKS
        run: |
          kubectl apply -f manifests/deployment.yaml --validate=false
